-- Creates the three empty training databases. Run as an administrator on the TRAINING instance only.
-- Dropping is deliberate: this script rebuilds the training data from scratch.
USE master;
GO
IF DB_ID('HK_SURAT') IS NOT NULL BEGIN ALTER DATABASE HK_SURAT SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE HK_SURAT; END;
IF DB_ID('HK_INDIA_A') IS NOT NULL BEGIN ALTER DATABASE HK_INDIA_A SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE HK_INDIA_A; END;
IF DB_ID('HK_INDIA_B') IS NOT NULL BEGIN ALTER DATABASE HK_INDIA_B SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE HK_INDIA_B; END;
GO
CREATE DATABASE HK_SURAT;
GO
CREATE DATABASE HK_INDIA_A;
GO
CREATE DATABASE HK_INDIA_B;
GO
